language: node_js
node_js:
  - 12

services: 
  - docker

script:
  # build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:v4
  - docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:v4
  - docker tag udagram-frontend "$DOCKER_USERNAME"/udagram-frontend:v4
  - docker tag udagram-reverseproxy "$DOCKER_USERNAME"/reverseproxy:v4

  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-api-feed:v4
  - docker push "$DOCKER_USERNAME"/udagram-api-user:v4
  - docker push "$DOCKER_USERNAME"/udagram-frontend:v4
  - docker push "$DOCKER_USERNAME"/reverseproxy:v4


  



