apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-user
  template:
    metadata:
      labels:
        service: udagram-user
    spec:
      containers:
        - name: chungvt
          image: chungvt/udagram-api-user:v1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
      restartPolicy: Always
