apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reverseproxy
  labels:
    app: backend-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-reverseproxy
  template:
    metadata:
      labels:
        app: backend-reverseproxy
    spec:
      containers:
      - name: backend-reverseproxy-node
        image: "chungvt/reverseproxy:v2"
        imagePullPolicy: Always
        resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "1024Mi"
                cpu: "500m"
        ports:
          - containerPort: 8080
          