apiVersion: v1
kind: Service
metadata:
  name: backend-reverseproxy
  labels:
    run: backend-reverseproxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: backend-reverseproxy